#ForgeLoginMod users. Passwords are PBKDF2 hashes, not decryptable passwords.
#Sat Oct 03 17:32:51 WAT 2026
adventuretest=v1$120000$Db_xRRDBJhD2QjglPwuG5w$hv9-LpIMrWSD1qx_us-rbc2CBQmYjQ-Hnny4Epy1Ul8
primordial=v1$120000$KRJ0tTzJc8AxO9jC2li1OA$Pn_LGor73lGhaSaHs0qdpNX99AltKN3_MTD_r0m3oAo
